services:
  - type: web
    name: absensiku
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: AbsensiKu
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:jrfduWS+vcCOD2wZ6ul+BLrIvoF3Isf3fWrpphIP3Z8=
      - key: DATABASE_URL
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: BCRYPT_ROUNDS
        value: "10"
